- LICENSE.txt
- README.md
- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
No
Docs
no readme, no license
readme + license
> Readmelicense

- powsybl-parent/pom.xml
NO
Feature
No groovydoc is generated.
Add groovydoc generation in -Prelease
NO
(also Cleanup remove useless execution)
(if any of the questions/checkboxes don't apply, please …
> Releasedocs

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
> prepare release v2

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
N/A
Bug fix
When `mvn install` is called, the groovydoc jar's extension is changed to a `.groovydoc`. Then when the release is checked by sonatype, the repository is not valid because the javadoc jar is missing.
We use build-helper maven plugin to attach the groovy doc jar as a javadoc jar.
**Does …
> Build helper

- .gitignore
- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
No
feature
Maven plugins have been updated to their last stable version, in particular gmavenplus plugin which has to be updated to be used with Groovy 3 
(if any of the …
> Update Maven plugins

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
Signed-off-by: Jon Harper <jon.harper87@gmail.com>
(if any of the questions/checkboxes don't apply, please delete them entirely)
> Release v5

- powsybl-build-tools/src/main/resources/powsybl-build-tools/checkstyle.xml
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
No
Feature
SingleSpaceSeparator has been added to checkstyle config
(if any of the questions/checkboxes don't apply, please delete them entirely)
> Add SingleSpaceSeparator checkstyle rule

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
No
Release
9-SNAPSHOT
10-SNAPSHOT
(if any of the questions/checkboxes don't apply, please delete them entirely)
> Prepare release 9

- powsybl-parent/powsybl-parent-ws/pom.xml
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/docs/git-describe.md#git-describe-and-a-small-gotcha-with-tags
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
NO
Feature
actuator/info has
```json
{
"commit": {
"id": {
"describe-short": "4e9e4a3-dirty", # or without "-dirty" if not 
"describe": "4e9e4a3-dirty"
},
"closest": { …
```
> use lightweight tags in git describe

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
> release v11

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
> prepare next release 12-SNAPSHOT

- powsybl-parent/pom.xml
> Update checkstyle to work with Java 17

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
No
New version
Bump to 14-SNAPSHOT
Merge it with the option Rebase and merge. **DO NOT squash the commit!**
> Prepare release 13 and open release 14

- powsybl-parent/powsybl-parent-ws/pom.xml
> Fix incompatibility between Liquibase and Hibernate with Spring Boot 3

- powsybl-parent/powsybl-parent-ws/pom.xml
> fix type change from uuid to bytea in liquibase diff

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
No
New version
Bump to 20-SNAPSHOT
Merge it with the option Rebase and merge. **DO NOT squash the commit!**
> Prepare release 19 and open release 20

- powsybl-parent/powsybl-parent-ws/pom.xml
> Springboot 3.3.3 migration

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
> Bump to v20

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
> Bump to v21-SNAPSHOT

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
> release v21

- pom.xml
No
Feature
Artifacts are uploaded to [OSSRH](https://oss.sonatype.org/)
Artifacts are uploaded to [Central Portal](https://central.sonatype.com/publishing)
**If yes, please check if the following requirements are fulfilled**
**What changes might users need to make in their application due to this PR? (migration steps)**
The breaking change only concernes people releasing new versions of a repository based on the present one.
You have to [generate a new token specific …
> Migrate Maven upload from OSSRH to Central Portal

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
**DO NOT SQUASH-MERGE!!!**
**If yes, please check if the following requirements are fulfilled**
**What changes might users need to make in their application due to this PR? (migration steps)**
> Prepare v23 release

- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
Prepare release v20.2
:warning: **DO NOT** squash the commits, merge with fast-forward locally
> Prepare release v20.2

- powsybl-build-tools/src/main/resources/powsybl-build-tools/checkstyle.xml
- powsybl-parent/pom.xml
No
Bug fix
Java 21 is not well supported since the last maven-checkstyle-plugin version (3.6.0 to date) [still relies by default on an old Checkstyle version](https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html) (v9.3).
For example, with the following code:
```java
@Override
public boolean equals(Object obj) {
if (obj instanceof IndexedName(String name1, int num1)) {
return name.equals(name1) && num == num1;
}
return false;
}
```
We get the following error during a `mvn clean install`:
`[ERROR] Failed to execute goal …
> Add checkstyle version and update checkstyle.xml header

- README.md
- pom.xml
- powsybl-build-tools/pom.xml
- powsybl-build-tools/src/main/resources/powsybl-build-tools/checkstyle.xml
- powsybl-parent/pom.xml
- powsybl-parent/powsybl-parent-ws/pom.xml
**WARNING: Do not merge on Github**
**If yes, please check if the following requirements are fulfilled**
**What changes might users need to make in their application due to this PR? (migration steps)**
> Prepare release v22.1
